language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1Kolesova-allLabs
  - make -j
  - ./PolinomialTest/PolinomialTest
notifications:
  email: false
