language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-1Kolesova-allLabs
  - make -j
  - ./Vectortest/VectorTest
  - ./MatrixTest/MatrixTest
notifications:
  email: false
